SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [MERGEPROCESS_New].[PreMerge]
	AS 
Declare @LogDate datetime = (Select getdate())

INSERT INTO MERGEPROCESS_New.LogPreMergeAccount
Select a.FK_MergeID,ObjectType, 'Winner' MergeRecordType, @LogDate LogDate, 
--updateme add prodcopy columns
Id,	IsDeleted,	MasterRecordId,	Name,	Type,	ParentId,	BillingStreet,	BillingCity,	BillingState,	BillingPostalCode,	BillingCountry,	BillingLatitude,	BillingLongitude,	BillingAddress,	ShippingStreet,	ShippingCity,	ShippingState,	ShippingPostalCode,	ShippingCountry,	ShippingLatitude,	ShippingLongitude,	ShippingAddress,	Phone,	Website,	PhotoUrl,	Industry,	NumberOfEmployees,	Description,	OwnerId,	CreatedDate,	CreatedById,	LastModifiedDate,	LastModifiedById,	SystemModstamp,	LastActivityDate,	LastViewedDate,	LastReferencedDate,	JigsawCompanyId,	Fax,	AnnualRevenue,	AccountSource,	SicDesc,	RecordTypeId,	Jigsaw,	hed__Current_Address__c,	hed__Primary_Contact__c,	SSB_CRMSYSTEM_ACCT_ID__c,	BillingGeocodeAccuracy,	ShippingGeocodeAccuracy,	copyloaddate,	SSB_CRMSYSTEM_SSID_Winner__c,	SSB_CRMSYSTEMFullArchticsIDs__c,	SSB_CRMSYSTEMDimCustomerIDs__c,	SSB_CRMSystemArchticsIDs__c,	SSB_LastPurchaseDate__c,	SSB_LastDonationDate__c,	SSB_IsDonor__c,	SSB_PriorityPoints__c,	SSB_FB_STH__c,	SSB_FB_STHRookie__c,	SSB_FB_PartialBuyer__c,	SSB_CRMSystem_SSIDWinnerSourceSystem__c,	Active__c,	CustomerPriority__c,	NumberofLocations__c,	SLAExpirationDate__c,	SLASerialNumber__c,	SLA__c,	SSB_CRMSYSTEM_APIID__c,	SSB_CRMSYSTEM_CY_Donation_Amount__c,	SSB_CRMSYSTEM_CY_Donation_Level__c,	SSB_CRMSYSTEM_CY_Donation_Upsell__c,	SSB_CRMSYSTEM_DimCustomerID__c,	SSB_CRMSYSTEM_Donor_Warning__c,	SSB_CRMSYSTEM_Football_Partial__c,	SSB_CRMSYSTEM_Football_Rookie__c,	SSB_CRMSYSTEM_Football_STH__c,	SSB_CRMSYSTEM_Last_Donation_Date__c,	SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c,	SSB_CRMSYSTEM_Mens_Basketball_Partial__c,	SSB_CRMSYSTEM_Mens_Basketball_Rookie__c,	SSB_CRMSYSTEM_Mens_Basketball_STH__c,	SSB_CRMSYSTEM_SSID_TIX__c,	SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c,	SSB_CRMSYSTEM_TIX_Account_ID__c,	SSB_CRMSYSTEM_Total_Priority_Points__c,	UpsellOpportunity__c
FROM MERGEPROCESS_New.Queue a
JOIN mergeprocess_new.tmp_pcaccount b
	ON a.Winning_ID = b.ID
UNION ALL
Select a.FK_MergeID,ObjectType, 'Loser' MergeRecordType, @LogDate LogDate, 
--updateme add prodcopy columns
Id,	IsDeleted,	MasterRecordId,	Name,	Type,	ParentId,	BillingStreet,	BillingCity,	BillingState,	BillingPostalCode,	BillingCountry,	BillingLatitude,	BillingLongitude,	BillingAddress,	ShippingStreet,	ShippingCity,	ShippingState,	ShippingPostalCode,	ShippingCountry,	ShippingLatitude,	ShippingLongitude,	ShippingAddress,	Phone,	Website,	PhotoUrl,	Industry,	NumberOfEmployees,	Description,	OwnerId,	CreatedDate,	CreatedById,	LastModifiedDate,	LastModifiedById,	SystemModstamp,	LastActivityDate,	LastViewedDate,	LastReferencedDate,	JigsawCompanyId,	Fax,	AnnualRevenue,	AccountSource,	SicDesc,	RecordTypeId,	Jigsaw,	hed__Current_Address__c,	hed__Primary_Contact__c,	SSB_CRMSYSTEM_ACCT_ID__c,	BillingGeocodeAccuracy,	ShippingGeocodeAccuracy,	copyloaddate,	SSB_CRMSYSTEM_SSID_Winner__c,	SSB_CRMSYSTEMFullArchticsIDs__c,	SSB_CRMSYSTEMDimCustomerIDs__c,	SSB_CRMSystemArchticsIDs__c,	SSB_LastPurchaseDate__c,	SSB_LastDonationDate__c,	SSB_IsDonor__c,	SSB_PriorityPoints__c,	SSB_FB_STH__c,	SSB_FB_STHRookie__c,	SSB_FB_PartialBuyer__c,	SSB_CRMSystem_SSIDWinnerSourceSystem__c,	Active__c,	CustomerPriority__c,	NumberofLocations__c,	SLAExpirationDate__c,	SLASerialNumber__c,	SLA__c,	SSB_CRMSYSTEM_APIID__c,	SSB_CRMSYSTEM_CY_Donation_Amount__c,	SSB_CRMSYSTEM_CY_Donation_Level__c,	SSB_CRMSYSTEM_CY_Donation_Upsell__c,	SSB_CRMSYSTEM_DimCustomerID__c,	SSB_CRMSYSTEM_Donor_Warning__c,	SSB_CRMSYSTEM_Football_Partial__c,	SSB_CRMSYSTEM_Football_Rookie__c,	SSB_CRMSYSTEM_Football_STH__c,	SSB_CRMSYSTEM_Last_Donation_Date__c,	SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c,	SSB_CRMSYSTEM_Mens_Basketball_Partial__c,	SSB_CRMSYSTEM_Mens_Basketball_Rookie__c,	SSB_CRMSYSTEM_Mens_Basketball_STH__c,	SSB_CRMSYSTEM_SSID_TIX__c,	SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c,	SSB_CRMSYSTEM_TIX_Account_ID__c,	SSB_CRMSYSTEM_Total_Priority_Points__c,	UpsellOpportunity__c
FROM MERGEPROCESS_New.Queue a
JOIN mergeprocess_new.tmp_pcaccount b
	ON a.Losing_ID = b.ID

INSERT INTO MERGEPROCESS_New.LogPreMergeContact
Select a.FK_MergeID,ObjectType, 'Winner' MergeRecordType, @LogDate LogDate, 
--updateme add prodcopy columns
Id,	IsDeleted,	MasterRecordId,	AccountId,	LastName,	FirstName,	Salutation,	Name,	OtherStreet,	OtherCity,	OtherState,	OtherPostalCode,	OtherCountry,	OtherLatitude,	OtherLongitude,	OtherGeocodeAccuracy,	OtherAddress,	MailingStreet,	MailingCity,	MailingState,	MailingPostalCode,	MailingCountry,	MailingLatitude,	MailingLongitude,	MailingGeocodeAccuracy,	MailingAddress,	Phone,	Fax,	MobilePhone,	HomePhone,	OtherPhone,	AssistantPhone,	ReportsToId,	Email,	Title,	Department,	AssistantName,	LeadSource,	Birthdate,	Description,	OwnerId,	HasOptedOutOfEmail,	DoNotCall,	CreatedDate,	CreatedById,	LastModifiedDate,	LastModifiedById,	SystemModstamp,	LastActivityDate,	LastCURequestDate,	LastCUUpdateDate,	LastViewedDate,	LastReferencedDate,	EmailBouncedReason,	EmailBouncedDate,	IsEmailBounced,	PhotoUrl,	Jigsaw,	JigsawContactId,	SSB_CRMSYSTEM_CONTACT_ID__c,	SSB_CRMSYSTEM_ACCT_ID__c,	Suffix__c,	hed__AlternateEmail__c,	hed__Citizenship__c,	hed__Country_of_Origin__c,	hed__Current_Address__c,	hed__Deceased__c,	hed__Do_Not_Contact__c,	hed__Ethnicity__c,	hed__Exclude_from_Household_Formal_Greeting__c,	hed__Exclude_from_Household_Informal_Greeting__c,	hed__Exclude_from_Household_Name__c,	hed__FERPA__c,	hed__Financial_Aid_Applicant__c,	hed__Gender__c,	hed__HIPAA_Detail__c,	hed__HIPAA__c,	hed__Military_Background__c,	hed__Military_Service__c,	hed__Naming_Exclusions__c,	hed__PreferredPhone__c,	hed__Preferred_Email__c,	hed__Primary_Address_Type__c,	hed__Primary_Household__c,	hed__Primary_Organization__c,	hed__Religion__c,	hed__Secondary_Address_Type__c,	hed__Social_Security_Number__c,	hed__UniversityEmail__c,	hed__WorkEmail__c,	hed__WorkPhone__c,	hed__Work_Address__c,	hed__is_Address_Override__c,	Primary_Academic_Program__c,	Primary_Department__c,	Primary_Educational_Institution__c,	Primary_Sports_Organization__c,	Primary_Student_Organization__c,	copyloaddate,	SSB_FB_PartialBuyer__c,	SSB_FB_STHRookie__c,	SSB_PriorityPoints__c,	SSB_IsDonor__c,	SSB_LastDonationDate__c,	SSB_LastPurchaseDate__c,	SSB_CRMSystemDimCustomerIDs__c,	SSB_CRMSystem_SSIDWinnerSourceSystem__c,	SSB_CRMSystemArchticsIDs__c,	SSB_CRMSystemFullArchticsIDs__c,	SSB_CRMSYSTEM_SSID_Winner__c,	ssb_fb_sth__c,	Gender__c,	Languages__c,	Last_Modified_Raw_Date_Time__c,	Level__c,	SSB_CRMSYSTEM_CY_Donation_Amount__c,	SSB_CRMSYSTEM_CY_Donation_Level__c,	SSB_CRMSYSTEM_CY_Donation_Upsell__c,	SSB_CRMSYSTEM_Company_Name__c,	SSB_CRMSYSTEM_CorporateBuyer_Flag__c,	SSB_CRMSYSTEM_DimCustomerID__c,	SSB_CRMSYSTEM_Donor_Warning__c,	SSB_CRMSYSTEM_Football_Partial__c,	SSB_CRMSYSTEM_Football_Rookie__c,	SSB_CRMSYSTEM_Football_STH__c,	SSB_CRMSYSTEM_Last_Donation_Date__c,	SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c,	SSB_CRMSYSTEM_Mens_Basketball_Partial__c,	SSB_CRMSYSTEM_Mens_Basketball_Rookie__c,	SSB_CRMSYSTEM_Mens_Basketball_STH__c,	SSB_CRMSYSTEM_SSID_TIX__c,	SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c,	SSB_CRMSYSTEM_Suffix__c,	SSB_CRMSYSTEM_TIX_Account_ID__c,	SSB_CRMSYSTEM_Total_Priority_Points__c
FROM MERGEPROCESS_New.Queue a
JOIN mergeprocess_new.tmp_pccontact b
	ON a.Winning_ID = b.ID
UNION ALL
Select a.FK_MergeID,ObjectType, 'Loser' MergeRecordType, @LogDate LogDate, 
--updateme add prodcopy columns
Id,	IsDeleted,	MasterRecordId,	AccountId,	LastName,	FirstName,	Salutation,	Name,	OtherStreet,	OtherCity,	OtherState,	OtherPostalCode,	OtherCountry,	OtherLatitude,	OtherLongitude,	OtherGeocodeAccuracy,	OtherAddress,	MailingStreet,	MailingCity,	MailingState,	MailingPostalCode,	MailingCountry,	MailingLatitude,	MailingLongitude,	MailingGeocodeAccuracy,	MailingAddress,	Phone,	Fax,	MobilePhone,	HomePhone,	OtherPhone,	AssistantPhone,	ReportsToId,	Email,	Title,	Department,	AssistantName,	LeadSource,	Birthdate,	Description,	OwnerId,	HasOptedOutOfEmail,	DoNotCall,	CreatedDate,	CreatedById,	LastModifiedDate,	LastModifiedById,	SystemModstamp,	LastActivityDate,	LastCURequestDate,	LastCUUpdateDate,	LastViewedDate,	LastReferencedDate,	EmailBouncedReason,	EmailBouncedDate,	IsEmailBounced,	PhotoUrl,	Jigsaw,	JigsawContactId,	SSB_CRMSYSTEM_CONTACT_ID__c,	SSB_CRMSYSTEM_ACCT_ID__c,	Suffix__c,	hed__AlternateEmail__c,	hed__Citizenship__c,	hed__Country_of_Origin__c,	hed__Current_Address__c,	hed__Deceased__c,	hed__Do_Not_Contact__c,	hed__Ethnicity__c,	hed__Exclude_from_Household_Formal_Greeting__c,	hed__Exclude_from_Household_Informal_Greeting__c,	hed__Exclude_from_Household_Name__c,	hed__FERPA__c,	hed__Financial_Aid_Applicant__c,	hed__Gender__c,	hed__HIPAA_Detail__c,	hed__HIPAA__c,	hed__Military_Background__c,	hed__Military_Service__c,	hed__Naming_Exclusions__c,	hed__PreferredPhone__c,	hed__Preferred_Email__c,	hed__Primary_Address_Type__c,	hed__Primary_Household__c,	hed__Primary_Organization__c,	hed__Religion__c,	hed__Secondary_Address_Type__c,	hed__Social_Security_Number__c,	hed__UniversityEmail__c,	hed__WorkEmail__c,	hed__WorkPhone__c,	hed__Work_Address__c,	hed__is_Address_Override__c,	Primary_Academic_Program__c,	Primary_Department__c,	Primary_Educational_Institution__c,	Primary_Sports_Organization__c,	Primary_Student_Organization__c,	copyloaddate,	SSB_FB_PartialBuyer__c,	SSB_FB_STHRookie__c,	SSB_PriorityPoints__c,	SSB_IsDonor__c,	SSB_LastDonationDate__c,	SSB_LastPurchaseDate__c,	SSB_CRMSystemDimCustomerIDs__c,	SSB_CRMSystem_SSIDWinnerSourceSystem__c,	SSB_CRMSystemArchticsIDs__c,	SSB_CRMSystemFullArchticsIDs__c,	SSB_CRMSYSTEM_SSID_Winner__c,	ssb_fb_sth__c,	Gender__c,	Languages__c,	Last_Modified_Raw_Date_Time__c,	Level__c,	SSB_CRMSYSTEM_CY_Donation_Amount__c,	SSB_CRMSYSTEM_CY_Donation_Level__c,	SSB_CRMSYSTEM_CY_Donation_Upsell__c,	SSB_CRMSYSTEM_Company_Name__c,	SSB_CRMSYSTEM_CorporateBuyer_Flag__c,	SSB_CRMSYSTEM_DimCustomerID__c,	SSB_CRMSYSTEM_Donor_Warning__c,	SSB_CRMSYSTEM_Football_Partial__c,	SSB_CRMSYSTEM_Football_Rookie__c,	SSB_CRMSYSTEM_Football_STH__c,	SSB_CRMSYSTEM_Last_Donation_Date__c,	SSB_CRMSYSTEM_Last_Ticket_Purchase_Date__c,	SSB_CRMSYSTEM_Mens_Basketball_Partial__c,	SSB_CRMSYSTEM_Mens_Basketball_Rookie__c,	SSB_CRMSYSTEM_Mens_Basketball_STH__c,	SSB_CRMSYSTEM_SSID_TIX__c,	SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c,	SSB_CRMSYSTEM_Suffix__c,	SSB_CRMSYSTEM_TIX_Account_ID__c,	SSB_CRMSYSTEM_Total_Priority_Points__c
FROM MERGEPROCESS_New.Queue a
JOIN mergeprocess_new.tmp_pccontact b
	ON a.Losing_ID = b.ID
GO
